In [1]:
import time
import random
import numpy as np

## 4.1 Exercise on Functions
### Task 1 - Unit Conversion Program

In [21]:
# Task 1: Measurement Converter

def convert_length(value, from_unit, to_unit):
    if from_unit == "m" and to_unit == "ft":
        return value * 3.28084
    elif from_unit == "ft" and to_unit == "m":
        return value / 3.28084

def convert_weight(value, from_unit, to_unit):
    if from_unit == "kg" and to_unit == "lbs":
        return value * 2.20462
    elif from_unit == "lbs" and to_unit == "kg":
        return value / 2.20462

def convert_volume(value, from_unit, to_unit):
    if from_unit == "l" and to_unit == "gal":
        return value * 0.264172
    elif from_unit == "gal" and to_unit == "l":
        return value / 0.264172


print("Unit Converter")
print("1. Length")
print("2. Weight")
print("3. Volume")

choice = input("Enter your choice (1/2/3): ")

value = float(input("Enter value: "))
from_unit = input("From unit: ").lower()
to_unit = input("To unit: ").lower()

if choice == "1":
    answer = convert_length(value, from_unit, to_unit)
    print("Converted value =", answer)

elif choice == "2":
    answer = convert_weight(value, from_unit, to_unit)
    print("Converted value =", answer)

elif choice == "3":
    answer = convert_volume(value, from_unit, to_unit)
    print("Converted value =", answer)

else:
    print("Invalid choice")

Unit Converter
1. Length
2. Weight
3. Volume
Converted value = 65.6168


### Task 2 - Mathematical Operations on a List of Numbers

In [25]:
# Task 2: Mathematical Expression

def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

print("Choose what you want to find:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")


choice = input("Enter your choice (1/2/3/4): ")

numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

print("\nYou entered:", numbers)

if choice == "1":
    result = calculate_sum(numbers)
    print("Operation selected: Sum")
    print("The sum of the numbers is:", result)

elif choice == "2":
    result = calculate_average(numbers)
    print("Operation selected: Average")
    print("The average of the numbers is:", round(result, 2))

elif choice == "3":
    result = find_maximum(numbers)
    print("Operation selected: Maximum")
    print("The maximum number is:", result)

elif choice == "4":
    result = find_minimum(numbers)
    print("Operation selected: Minimum")
    print("The minimum number is:", result)

else:
    print("Invalid choice. Please run the program again.")

Choose what you want to find:
1. Sum
2. Average
3. Maximum
4. Minimum

You entered: [2.0, 3.0, 4.0, 5.0, 5.0, 6.0, 76.0, 67.0, 7.0, 7.0, 7.0, 7.0, 7.0, 4.0, 3.0, 2.0, 2222.0]
Operation selected: Average
The average of the numbers is: 143.18


## 4.2 Exercise on List Manipulation

In [26]:
def extract_every_other(lst):
    return lst[::2]

my_list = [1, 2, 3, 4, 5, 6]
extracted_list = extract_every_other(my_list)

print("First list:", my_list)
print("Every other element from the first list is:", extracted_list)
print()

my_list_2 = ['a', 'b', 'c', 'd', 'e']
extracted_list_2 = extract_every_other(my_list_2)

print("Second list:", my_list_2)
print("Every other element from the second list is:", extracted_list_2)

First list: [1, 2, 3, 4, 5, 6]
Every other element from the first list is: [1, 3, 5]

Second list: ['a', 'b', 'c', 'd', 'e']
Every other element from the second list is: ['a', 'c', 'e']


In [28]:
# 3. Get Sublist using Slicing

def get_sublist(lst, start, end):
    return lst[start:end+1]

my_list = [1, 2, 3, 4, 5, 6]
sub_list = get_sublist(my_list, 2, 4)

print("Original list 1:", my_list)
print("Start index: 2")
print("End index: 4")
print("The sublist from index 2 to 4 is:", sub_list)

my_list_2 = ['a', 'b', 'c', 'd', 'e']
sub_list_2 = get_sublist(my_list_2, 0, 2)

print("Original list 2:", my_list_2)
print("Start index: 0")
print("End index: 2")
print("The sublist from index 0 to 2 is:", sub_list_2)

Original list 1: [1, 2, 3, 4, 5, 6]
Start index: 2
End index: 4
The sublist from index 2 to 4 is: [3, 4, 5]
Original list 2: ['a', 'b', 'c', 'd', 'e']
Start index: 0
End index: 2
The sublist from index 0 to 2 is: ['a', 'b', 'c']


In [29]:
# 4. Remove First and Last Elements

def remove_first_last(lst):
    return lst[1:-1]

list1 = [1, 2, 3, 4, 5]
result1 = remove_first_last(list1)

print("For the first list:")
print("Original list =", list1)
print("New list after removing first and last elements =", result1)
print()

list2 = ['a', 'b', 'c', 'd', 'e']
result2 = remove_first_last(list2)

print("For the second list:")
print("Original list =", list2)
print("New list after removing first and last elements =", result2)

For the first list:
Original list = [1, 2, 3, 4, 5]
New list after removing first and last elements = [2, 3, 4]

For the second list:
Original list = ['a', 'b', 'c', 'd', 'e']
New list after removing first and last elements = ['b', 'c', 'd']


In [30]:
# 5. Get the First n Elements

def get_first_n(lst, n):
    return lst[:n]

list1 = [1, 2, 3, 4, 5, 6, 7, 8]
n1 = 3
result1 = get_first_n(list1, n1)

print("For the first list:")
print("Original list =", list1)
print("n =", n1)
print("New list with first n elements =", result1)
print()

list2 = ['a', 'b', 'c', 'd', 'e']
n2 = 2
result2 = get_first_n(list2, n2)

print("For the second list:")
print("Original list =", list2)
print("n =", n2)
print("New list with first n elements =", result2)

For the first list:
Original list = [1, 2, 3, 4, 5, 6, 7, 8]
n = 3
New list with first n elements = [1, 2, 3]

For the second list:
Original list = ['a', 'b', 'c', 'd', 'e']
n = 2
New list with first n elements = ['a', 'b']


In [31]:
# 6. Extract Elements from the End

def get_last_n(lst, n):
    return lst[-n:]

my_list = [1, 2, 3, 4, 5, 6, 7, 8]

print("Original list:", my_list)

n1 = 3
print("When n =", n1)
print("The last", n1, "elements are:", get_last_n(my_list, n1))
print()

n2 = 5
print("When n =", n2)
print("The last", n2, "elements are:", get_last_n(my_list, n2))
print()

n3 = 1
print("When n =", n3)
print("The last", n3, "element is:", get_last_n(my_list, n3))

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
When n = 3
The last 3 elements are: [6, 7, 8]

When n = 5
The last 5 elements are: [4, 5, 6, 7, 8]

When n = 1
The last 1 element is: [8]


In [32]:
# 7. Extract Elements in Reverse Order

def reverse_skip(lst):
    return lst[-2::-2]

list1 = [1, 2, 3, 4, 5, 6]
print("For the first list:")
print("Original list =", list1)
print("Output =", reverse_skip(list1))
print()

list2 = [10, 20, 30, 40, 50]
print("For the second list:")
print("Original list =", list2)
print("Output =", reverse_skip(list2))
print()

list3 = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print("For the third list:")
print("Original list =", list3)
print("Output =", reverse_skip(list3))

For the first list:
Original list = [1, 2, 3, 4, 5, 6]
Output = [5, 3, 1]

For the second list:
Original list = [10, 20, 30, 40, 50]
Output = [40, 20]

For the third list:
Original list = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
Output = ['f', 'd', 'b']


## 4.3 Exercise on Nested List

In [33]:
# Nested List Operations

def flatten(lst):
    result = []
    for item in lst:
        if type(item) == list:
            result += flatten(item)
        else:
            result.append(item)
    return result

def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

def sum_nested(lst):
    total = 0
    for item in lst:
        if type(item) == list:
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    result = []
    for item in lst:
        if type(item) == list:
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

def find_max(lst):
    flat_list = flatten(lst)
    return max(flat_list)

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if type(item) == list:
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    return flatten(lst)

def average_nested(lst):
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)


# Example lists
nested_1 = [[1, 2], [3, 4], [5]]
nested_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nested_3 = [[1, 2], [3, [4, 5]], 6]
nested_4 = [[1, 2], [3, 2], [4, 5]]
nested_5 = [[1, 2], [2, 3], [2, 4]]
nested_6 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
nested_7 = [[1, 2], [3, 4], [5, 6]]

print("Nested List Operation")

print("\n1. Flatten a nested list")
print("Original list:", nested_1)
print("Flattened list:", flatten(nested_1))

print("\n2. Access an element from nested list")
print("Original list:", nested_2)
print("Index path: [1, 2]")
print("Element found:", access_nested_element(nested_2, [1, 2]))

print("\n3. Find the sum of all elements in nested list")
print("Original list:", nested_3)
print("Sum of all elements:", sum_nested(nested_3))

print("\n4. Remove an element from nested list")
print("Original list:", nested_4)
print("Element to remove: 2")
print("New list after removing 2:", remove_element(nested_4, 2))

print("\n5. Find the maximum element in nested list")
print("Original list:", nested_3)
print("Maximum element:", find_max(nested_3))

print("\n6. Count occurrences of an element")
print("Original list:", nested_5)
print("Element to count: 2")
print("Number of times 2 appears:", count_occurrences(nested_5, 2))

print("\n7. Deep flatten a nested list")
print("Original list:", nested_6)
print("Fully flattened list:", deep_flatten(nested_6))

print("\n8. Find average of all elements in nested list")
print("Original list:", nested_7)
print("Average of all elements:", average_nested(nested_7))

Nested List Operation

1. Flatten a nested list
Original list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]

2. Access an element from nested list
Original list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Index path: [1, 2]
Element found: 6

3. Find the sum of all elements in nested list
Original list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21

4. Remove an element from nested list
Original list: [[1, 2], [3, 2], [4, 5]]
Element to remove: 2
New list after removing 2: [[1], [3], [4, 5]]

5. Find the maximum element in nested list
Original list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6

6. Count occurrences of an element
Original list: [[1, 2], [2, 3], [2, 4]]
Element to count: 2
Number of times 2 appears: 3

7. Deep flatten a nested list
Original list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Fully flattened list: [1, 2, 3, 4, 5, 6, 7, 8]

8. Find average of all elements in nested list
Original list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


## 10.1 Basic Vector and Matrix Operation with NumPy
### Problem 1 - Array Creation

In [34]:
# 1. Initialize an empty array with size 2x2
empty_array_2x2 = np.empty((2, 2))

# 2. Initialize an all-one array with size 4x2
ones_array_4x2 = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7, dtype=int)

# 4. Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(reference_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(reference_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)

print("1. Empty 2x2 array:\n", empty_array_2x2)
print("\n2. Ones 4x2 array:\n", ones_array_4x2)
print("\n3. Full array:\n", full_array)
print("\n4. Zeros like reference array:\n", zeros_like_array)
print("\n5. Ones like reference array:\n", ones_like_array)
print("\n6. NumPy array from list:\n", numpy_array_from_list)

1. Empty 2x2 array:
 [[23. 51.]
 [13. 29.]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like reference array:
 [[0. 0. 0.]
 [0. 0. 0.]]

5. Ones like reference array:
 [[1. 1. 1.]
 [1. 1. 1.]]

6. NumPy array from list:
 [1 2 3 4]


### Problem 2 - Array Manipulation: Numerical Ranges and Array Indexing

In [39]:
import numpy as np

# 1. Create an array with values from 10 to 49
arr_10_to_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:")
print(arr_10_to_49)
print()

# 2. Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix with values from 0 to 8:")
print(matrix_3x3)
print()

# 3. Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("3. 3x3 identity matrix:")
print(identity_3x3)
print()

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
print("4. Random array of size 30:")
print(random_array_30)
print("Mean of the array is:", random_array_30.mean())
print()

# 5. Create a 10x10 random array and find minimum and maximum
random_10x10 = np.random.random((10, 10))
print("5. Random 10x10 array:")
print(random_10x10)
print("Minimum value in the array is:", random_10x10.min())
print("Maximum value in the array is:", random_10x10.max())
print()

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1
print("6. Zero array of size 10 after replacing the 5th element with 1:")
print(zero_array_10)
print()

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7. Original array:")
print(arr)
print("Reversed array:")
print(reversed_arr)
print()

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:")
print(border_array)
print()

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 checkerboard pattern:")
print(checkerboard)

1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.39705318 0.12390618 0.51192185 0.49877954 0.18134378 0.62146362
 0.31728698 0.0667511  0.26531853 0.280619   0.86050464 0.4901518
 0.97442685 0.27540322 0.40348826 0.99827392 0.24504095 0.70464785
 0.36660469 0.40256283 0.44543094 0.74593288 0.81038186 0.48969652
 0.29164537 0.348441   0.6761236  0.25887504 0.84241333 0.88611328]
Mean of the array is: 0.49268675294992403

5. Random 10x10 array:
[[0.73582156 0.41822785 0.79338373 0.43950819 0.19584032 0.03850712
  0.56335989 0.55700759 0.56214755 0.05722272]
 [0.52896676 0.82755959 0.912918   0.82111653 0.62104252 0.32200166
  0.38318085 0.0338321  0.00975998 0.79797406]
 [0.38221105 0.60863288 0.73451389 0.65317599 0.565

### Problem 3 - Array Operations

In [36]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y

# 2. Subtract the two arrays
subtract_xy = x - y

# 3. Multiply the arrays with integers of choice
x_times_3 = x * 3
y_times_2 = y * 2
v_times_4 = v * 4
w_times_5 = w * 5

# 4. Square each element
x_squared = np.square(x)
y_squared = np.square(y)
v_squared = np.square(v)
w_squared = np.square(w)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

# 6. Concatenate x and y along rows, concatenate v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.column_stack((v, w))

print("1. x + y:\n", add_xy)
print("\n2. x - y:\n", subtract_xy)
print("\n3. x * 3:\n", x_times_3)
print("y * 2:\n", y_times_2)
print("v * 4:\n", v_times_4)
print("w * 5:\n", w_times_5)
print("\n4. Square of x:\n", x_squared)
print("Square of y:\n", y_squared)
print("Square of v:\n", v_squared)
print("Square of w:\n", w_squared)
print("\n5. Dot product v . w:", dot_vw)
print("Dot product x . v:\n", dot_xv)
print("Dot product x . y:\n", dot_xy)
print("\n6. Concatenate x and y along rows:\n", concat_xy_rows)
print("\nConcatenate v and w along columns:\n", concat_vw_columns)

print("\n7. Concatenate x and v:")
try:
    bad_concat = np.concatenate((x, v), axis=0)
    print(bad_concat)
except ValueError as e:
    print("Error:", e)
    print(
        "Explanation: x is a 2D array with shape", x.shape,
        "but v is a 1D array with shape", v.shape,
        ". NumPy cannot concatenate arrays with different numbers of dimensions."
    )

# Correct way to combine x and v if needed:
v_as_row = v.reshape(1, 2)
fixed_concat = np.concatenate((x, v_as_row), axis=0)
print("\nCorrected concatenation after reshaping v to (1, 2):\n", fixed_concat)

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]
y * 2:
 [[10 12]
 [14 16]]
v * 4:
 [36 40]
w * 5:
 [55 60]

4. Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]

5. Dot product v . w: 219
Dot product x . v:
 [29 77]
Dot product x . y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array with shape (2, 2) but v is a 1D array with shape (2,) . NumPy cannot concatenate arrays with different numbers of dimensions.

Corrected concatenation after reshaping v to (1, 2):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


### Problem 4 - Matrix Operations

In [42]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print(f"Given matrices:\nA = \n{A}\nB = \n{B}")

# 1. Prove A.A⁻¹ = I
inverse_A = np.linalg.inv(A)
product_A_invA = np.dot(A, inverse_A)
identity_matrix = np.eye(2)

print(f"\n1. Proving A.A⁻¹ = I:")
print(f"Inverse of A is:\n{inverse_A}")
print(f"A . A⁻¹ =\n{product_A_invA}")
print(f"Identity matrix I =\n{identity_matrix}")
print(f"Is A . A⁻¹ approximately equal to I? {np.allclose(product_A_invA, identity_matrix)}")

# 2. Prove AB ≠ BA
product_AB = np.dot(A, B)
product_BA = np.dot(B, A)

print(f"\n2. Proving AB ≠ BA:")
print(f"A . B =\n{product_AB}")
print(f"B . A =\n{product_BA}")
print(f"Is A . B equal to B . A? {np.array_equal(product_AB, product_BA)}")

# 3. Prove (AB)ᵀ = BᵀAᵀ
product_AB_T = np.transpose(product_AB)
transpose_B = np.transpose(B)
transpose_A = np.transpose(A)
product_BT_AT = np.dot(transpose_B, transpose_A)

print(f"\n3. Proving (AB)ᵀ = BᵀAᵀ:")
print(f"(A . B)ᵀ =\n{product_AB_T}")
print(f"Bᵀ . Aᵀ =\n{product_BT_AT}")
print(f"Is (A . B)ᵀ approximately equal to Bᵀ . Aᵀ? {np.allclose(product_AB_T, product_BT_AT)}")

Given matrices:
A = 
[[3 4]
 [7 8]]
B = 
[[5 3]
 [2 1]]

1. Proving A.A⁻¹ = I:
Inverse of A is:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A . A⁻¹ =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I =
[[1. 0.]
 [0. 1.]]
Is A . A⁻¹ approximately equal to I? True

2. Proving AB ≠ BA:
A . B =
[[23 13]
 [51 29]]
B . A =
[[36 44]
 [13 16]]
Is A . B equal to B . A? False

3. Proving (AB)ᵀ = BᵀAᵀ:
(A . B)ᵀ =
[[23 51]
 [13 29]]
Bᵀ . Aᵀ =
[[23 51]
 [13 29]]
Is (A . B)ᵀ approximately equal to Bᵀ . Aᵀ? True


### Solve the System of Linear Equations


In [43]:
# Represent the system AX = C
coeff_matrix = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
], dtype=float)

constants = np.array([-1, -3, 9], dtype=float)

# Method 1: Solve directly using np.linalg.solve
solution_solve = np.linalg.solve(coeff_matrix, constants)

# Method 2: Solve using the inverse matrix
coeff_matrix_inv = np.linalg.inv(coeff_matrix)
solution_inv = coeff_matrix_inv @ constants

print("Coefficient matrix A:\n", coeff_matrix)
print("\nConstant vector C:\n", constants)
print("\nSolution using np.linalg.solve:")
print(f"x = {solution_solve[0]}, y = {solution_solve[1]}, z = {solution_solve[2]}")

print("\nSolution using np.linalg.inv(A) @ C:")
print(f"x = {solution_inv[0]}, y = {solution_inv[1]}, z = {solution_inv[2]}")

print("\nDo both methods match?", np.allclose(solution_solve, solution_inv))

Coefficient matrix A:
 [[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]

Constant vector C:
 [-1. -3.  9.]

Solution using np.linalg.solve:
x = 2.0, y = 1.0000000000000002, z = -2.0

Solution using np.linalg.inv(A) @ C:
x = 2.0, y = 1.0, z = -2.0

Do both methods match? True


## 10.2 

In [11]:
# Shared data for 1,000,000-element experiments
SIZE = 1_000_000
list_a = [random.random() for _ in range(SIZE)]
list_b = [random.random() for _ in range(SIZE)]

np_a = np.array(list_a)
np_b = np.array(list_b)

### 1. Element-wise Addition

In [12]:
# Python lists
start = time.perf_counter()
list_add_result = [a + b for a, b in zip(list_a, list_b)]
end = time.perf_counter()
python_add_time = end - start

# NumPy arrays
start = time.perf_counter()
numpy_add_result = np_a + np_b
end = time.perf_counter()
numpy_add_time = end - start

print(f"Python list addition time: {python_add_time:.6f} seconds")
print(f"NumPy array addition time: {numpy_add_time:.6f} seconds")
print(f"Speedup: {python_add_time / numpy_add_time:.2f}x")

Python list addition time: 0.072357 seconds
NumPy array addition time: 0.003912 seconds
Speedup: 18.49x


### 2. Element-wise Multiplication

In [13]:
# Python lists
start = time.perf_counter()
list_mul_result = [a * b for a, b in zip(list_a, list_b)]
end = time.perf_counter()
python_mul_time = end - start

# NumPy arrays
start = time.perf_counter()
numpy_mul_result = np_a * np_b
end = time.perf_counter()
numpy_mul_time = end - start

print(f"Python list multiplication time: {python_mul_time:.6f} seconds")
print(f"NumPy array multiplication time: {numpy_mul_time:.6f} seconds")
print(f"Speedup: {python_mul_time / numpy_mul_time:.2f}x")

Python list multiplication time: 0.071303 seconds
NumPy array multiplication time: 0.004019 seconds
Speedup: 17.74x


### 3. Dot Product

In [14]:
# Python lists
start = time.perf_counter()
list_dot_result = sum(a * b for a, b in zip(list_a, list_b))
end = time.perf_counter()
python_dot_time = end - start

# NumPy arrays
start = time.perf_counter()
numpy_dot_result = np.dot(np_a, np_b)
end = time.perf_counter()
numpy_dot_time = end - start

print(f"Python list dot product time: {python_dot_time:.6f} seconds")
print(f"NumPy array dot product time: {numpy_dot_time:.6f} seconds")
print(f"Speedup: {python_dot_time / numpy_dot_time:.2f}x")
print(f"Are the results close? {np.isclose(list_dot_result, numpy_dot_result)}")

Python list dot product time: 0.049490 seconds
NumPy array dot product time: 0.001484 seconds
Speedup: 33.34x
Are the results close? True
